### PR TITLE
Implement Entity UI

### PR DESCRIPTION
**Pull request by heymatthenry**
# What this PR does

This PR addresses GSA-TTS/FAC#170, implementing queries to the API to validate UEIs and present validation results to the user:
 
chrome-capture-2022-4-16

👀 [Preview build](https://federalist-9a617ff8-042d-4076-9581-bb999f9c6639.app.cloud.gov/preview/gsa-tts/fac-frontend/mh-entity-information-170/audit/new/step-2/)

However, it also does quite a bit more. In order to support the client-side validations on this and other pages, it does the following extra stuff:

* [x] abstracts validations into a separate library (0be9282);
* [x] introduces `esbuild` so we can use ES module imports in client-side code (to bring that validation code in where it's needed) (733bfff); and
* [x] adds [jest](https://jestjs.io/) and tests for the new library code (e1077e7)

# What this PR does _not_ do

* Validate dates
* Submit the form to the backend

### CODE REVIEW

**Comment by petermarks-gsa** [comment]
@heymatthenry Love preview build! A+ pull request :) 

I ran through the acceptance criteria defined in https://github.com/GSA-TTS/FAC/issues/126

- ✅ When a user can have an entity name (or list of names) returned after they enter a UEI
  - ✅ Valid UEI (ZQGGHJH74DW7) shows success message + match of organization name
  - ✅ Invalid UEI (ASDFGJASDFGJ) shows "UEI was not found in SAM.gov"
    - Non blocking request for slight tweak - can the error messages read "can't be blank" instead of "can't be null?"
- ❓When a user can choose the entity name they'd like to proceed with 
  - Are there cases where multiple entity names will show up? Do you have example UEI's if so? 
- ❌ The entity name they've chosen is pre-populated in the name field
  - Assuming this means the "Auditee name" filed is filled in automatically, this is not working as expected. 
- ❓Has SAM.gov connectivity error copy been ported over from https://github.com/GSA-TTS/FAC/issues/165 ? If so, is there a way to test? I don't mind Chrome console hacks to test :)

**Comment by MelissaBraxton** [comment]
- The auditee name field should be disabled when users arrive to the page. 
- Name should be auto-populated into the name field based on UEI lookup, and the name field should remain disabled.
- If there is no UEI found and they choose to continue without a validated UEI, we will want to enable data entry into the name field. they'll have to enter a name in order to proceed, but they'll have to come back and enter a valid UEI / name before their submission can be certified.

**Comment by heymatthenry** [comment]
Thanks for that, @MelissaBraxton!

@petermarks-gsa The field is now disabled and will populate automatically with the response from the API:

chrome-capture-2022-4-16 (1)
.

**Comment by petermarks-gsa** [comment]
@heymatthenry This now appears to be working as @MelissaBraxton specified. However, I'm a little concerned that folks will not know to click the "Validate UEI" link. I'm wondering if it would be appropriate to automatically validate UEI when the cursor leaves the "Re-enter Auditee Unique Entity Identifier (UEI)"?

**Comment by heymatthenry** [comment]
@petermarks-gsa We can absolutely do that. My only concern is that, given it's an API call, we might get into a situation where a user fires off multiple requests in a short amount of time which feels like a source of bugs.

**Comment by petermarks-gsa** [comment]
@heymatthenry I feel like a cursor existing a that last will not happen too often. I'm honestly not sure why a user would think to click that link unless they enter a new UEI. Curious if you have thoughts on my previous comment / design feedback @MelissaBraxton

**Comment by heymatthenry** [comment]
@petermarks-gsa Cool. If we get consensus on that, we can just do the query on blur. The only other question/concern I have is about whether we should remove the button: on one hand, if we're doing it automatically, it might be confusing to keep the button. But on the other hand, it can be an accessibility issue to have an important action with no way to manually trigger it.

**Review by geekygirlsarah — APPROVED** [review]

**Comment by petermarks-gsa** [comment]
@MelissaBraxton @austinhernandez defer to your testing on this. 

@heymatthenry This is approved from a QA standpoint. Thanks for the responsive feedback!

**Pull request merged**
