### PR TITLE
Add explanatory tooltip to validate UEI button

### PR DESCRIPTION
**Pull request by heymatthenry**
This PR adds a tooltip to explain the process of validating UEIs as described in GSA-TTS/FAC#145.

image

👀 [Federalist preview](https://federalist-9a617ff8-042d-4076-9581-bb999f9c6639.app.cloud.gov/preview/gsa-tts/fac-frontend/mh-uei-tooltip-145/audit/new/step-2/)

### CODE REVIEW

**Comment by MelissaBraxton** [comment]
How much of a lift is it to work in a line break? Thinking about potential accessibility issues with the text on the left being covered when the tool tip is open.

**Comment by heymatthenry** [comment]
@MelissaBraxton I played around with it some, and couldn't get it to work with the stock USWDS component. We'd have to do it from scratch, which wouldn't be a huge lift, but maybe a couple hours of work. You get a lot of good stuff for free from the USWDS component that we'd have to do by hand. I think the accessibility hit from having the long text is pretty small since it disappears when the button loses focus.

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Flagging that I think we need a decision here one way or another to get this past the finish line.

**Review by MelissaBraxton — APPROVED** [review]
Let's proceed with the USWDS component as is. We'll make a point to get user feedback on this in the coming weeks, and we can refine later as needed.

**Pull request merged**
