### PR TITLE
343: UI when user does not have any submissions

### PR DESCRIPTION
**Pull request by rachelschneiderman**
image

image

### CODE REVIEW

**Comment by austinhernandez** [comment]
Thank you for flagging the error state. The only thing I would change is moving the error list to the top so that when it's read by a screenreader, the errors precede the checkbox [like on this error state](https://designsystem.digital.gov/components/file-input/) 

example!
Screen Shot 2022-07-18 at 12 59 11 PM

**Comment by rachelschneiderman** [comment]
> Thank you for flagging the error state. The only thing I would change is moving the error list to the top so that when it's read by a screenreader, the errors precede the checkbox [like on this error state](https://designsystem.digital.gov/components/file-input/)
> 
> example! Screen Shot 2022-07-18 at 12 59 11 PM

Got it, makes sense! Thank you so much!

**Comment by rachelschneiderman** [comment]
> Thank you for flagging the error state. The only thing I would change is moving the error list to the top so that when it's read by a screenreader, the errors precede the checkbox [like on this error state](https://designsystem.digital.gov/components/file-input/)
> 
> example! Screen Shot 2022-07-18 at 12 59 11 PM

Updated!

image

**Comment by austinhernandez** [comment]
I did a thumbs up emoji, but wanted to clearly express it looks good from a design perspective and that pattern can be carried throughout!

**Comment by rachelschneiderman** [comment]
Closing this PR for now while we wait to chat with Census in order to finalize the design/flow of starting a new submission.

**Pull request closed without merging**
